sudo: required
services:
  - docker

script:
  - docker build -t sid7631/node .
  - docker tag sid7631/node:latest sid7631/node:latest
  - docker images sid7631/node

before_deploy:
  - docker login -u sid7631 -p hazgi0-wucruG-dukxac

deploy:
  provider: script
  script: docker push sid7631/node:latest
  on:
    branch: main